### ISSUE TITLE
Framework not found

### ISSUE THREAD

**Issue by rebeloper** [eyeson-team/ios-sdk#2]
Hi,

After I install via SPM I get this error:

![CleanShot 2022-11-10 at 04 34 50@2x](https://user-images.githubusercontent.com/2488011/200986599-40e70d44-d1fd-452d-9386-e1bf142a22bd.png)

Could it be because I'm on macOS Ventura?

Thanks

**Comment by mmaier** [comment]
Hi,

it seems there is a deprecated framework dependency in your target. In the project navigator, can you check under your target > General > Frameworks, Libraries, and Embedded Content if there is an unavailable Eyeson framework left? If so, please remove it. There should now be an EyesonSdk framework if you have added the SPM dependency correctly.

Br
